title: KanBan WebApp
theme: jekyll-theme-minimal
mermaid:
  version: "10.9.0" 
callouts:
  tip:
    title: ğŸ¤ Tip
    color: purple
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Attention
    color: yellow
  download:
    title: ğŸ’¾ Download
    color: grey-dk
<<<<<<< HEAD

search_enabled: true
color_scheme: light
=======
>>>>>>> refs/remotes/origin/main
